### ISSUE TITLE
Training epochs

### ISSUE THREAD

**Issue by Maryeon** [msakarvadia/memorization#51]
Thanks for sharing the codes. I wonder how many epochs the toy models are trained on noise artifacts and backdoor artifacts?

I trained a 4-layer model with backdoor artifacts and found that after 5 epochs, the percent of memorized sequence saturates to 100%, although the default epoch is 200 according to the `memorization_in_toy_models.py`.

By the way, the IndexedDataset class is missing in the provided source code.

**Comment by msakarvadia** [comment]
Preprint: https://arxiv.org/pdf/2410.02159

RE Training epochs:
- Math+Noise: 3500 epochs
- Math+backdoor 500 epochs
- Language+Noise: 100 epochs
- Language+Backdoor: 50 epochs
- To see how many epochs we trained on I refer you to Figure 6 in appendix A.1 (screenshot below.
<img width="440" alt="image" src="https://github.com/user-attachments/assets/aa4a9aef-13c9-44ff-9b53-be7acc78fc02" />

RE Backdoor memorizing saturating to 100% in 5 epochs: We have the same behavior on our end (see Figure 6). Noise artifact memorization on the other hand takes a long time in comparison to backdoor artifacts. We designed the TinyMem model suite to have a wide variety of memorization styles/artifacts so that mitigation strategies could be tested in a wide variety of settings. Our results in Tables 1 & 2, Figure 3 in the preprint show that the backdoor artifacts are harder to mitigate compared to the noise artifacts. We speculate that this is because backdoor artifacts are easier to memorize than noise artifacts. Because we include both easy-to-memorize and hard-to-memorize artifacts in TinyMem, we found that the memorization mitigation strategies that worked best on production-grade models were those that did well in both settings.

RE  IndexedDataset: Can you point me to the line in the code where you are seeing this class? It is possible that you are seeing an outdated artifact from an earlier version of the code that got left behind.

Feel free to let me know if you have any more questions.

**Comment by Maryeon** [comment]
In `memorization_in_toy_models.py`, the IndexedDataset is imported in line 17 and referenced in line 157. There seems not a src.data.IndexedDataset module.

**Comment by msakarvadia** [comment]
Thanks for letting me know about that import. It was indeed an old import that should have been removed. 

I fixed the issue in the latest commit: https://github.com/msakarvadia/memorization/commit/fa4cc797db2e95ec0498350db58c5da12ec2d811

This should resolve the issue; please let me know if there are any further questions.
